Exercise26
clucksupremacy/beginner-friendly-programming-exercises pull request #27
Opened 2024-08-24 01:25 UTC by clucksupremacy

2024-08-24 03:24 UTC, Aceeri requested changes

2024-08-24 03:24 UTC, Aceeri commented on exercise-26.js
> +        const prompt = require("prompt-sync")({ sigint: true });
Try moving this outside of the functions, people tend to use these are global imports.

2024-08-24 03:24 UTC, Aceeri commented on exercise-26.js
> +    function calculate_avg_price() {
Also move these functions outside of the function above.

2024-08-24 03:24 UTC, Aceeri commented on exercise-26.js
> +    function compare_prices() {
Actually try just doing these with loops instead of recursive functions.

2024-08-27 00:03 UTC, clucksupremacy commented
Changes made @Aceeri

2024-08-27 07:42 UTC, Aceeri commented on exercise-26.js
> +    let sum = 0;
Try moving these into the functions they are related to

2024-08-29 00:40 UTC, merged